name: Push to registry 

on:
  push:
    branches:
      - 'master'

jobs:
  push_to_registry:
    name: Push Docker image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v3
    
      - name: Logging into registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: ${{ secrets.REGISTRY_URL }}
      
      - name: Extracting metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.REGISTRY_URL }}/${{ github.repository }}
      
      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}